export const products = [
    {
        id: 1,
        title: "Ooty",
        description: "Ooty-queen of hill stations",
        price: "5000",
        img: "./images/ooty.jpg",
        quantity: 1,
    },
    {
        id: 2,
        title: "Goa",
        description: "paradise of South Asia",
        price: "9300",
        img: "./images/goa.jpg",
        quantity: 1,
    },
    {
        id: 3,
        title: "Himachal",
        description: "mountains are calling",
        price: "8500",
        img: "./images/himachal.jpg",
        quantity: 1,
    },
    {
        id: 4,
        title: "Kashmir",
        description: "more beautiful than the heaven",
        price: "10500",
        img: "./images/kashmir.jpg",
        quantity: 1,
    },
    {
        id: 5,
        title: "Maldives",
        description: "life at blue beach",
        price: "50500",
        img: "./images/maldives.jpg",
        quantity: 1,
    },
    {
        id: 6,
        title: "Rajasthan",
        description: "glittering jewel of India",
        price: "9500",
        img: "./images/rajasthan.jpg",
        quantity: 1,
    },
    {
        id: 7,
        title: "Kerala",
        description: "The Land of Beauty and Wonders",
        price: "12500",
        img: "./images/kerala.jpg",
        quantity: 1,
    },
    {
        id: 8,
        title: "Gujarat",
        description: "Jewel of the West",
        price: "9500",
        img: "./images/gujarat.jpg",
        quantity: 1,
    },
    {
        id: 9,
        title: "Haridwar",
        description: "holy place with open heart",
        price: "7500",
        img: "./images/haridwar.jpg",
        quantity: 1,
    },
];